### ISSUE TITLE
auto-find names, page list, allow signs on walls

### ISSUE THREAD

**Issue by TNTUP** [tastybento/welcomewarpsigns#1]
1. What I mean by "auto-find names" is doing like /wwarp TNT will warp to TNTUP's warp;
2. Having too many names can spam the chat, like limiting 10 or 20 per page;
3. Allowing signs to be placed on the wall, currentely it says its not safe, although I verify and its safe, if it detects a lava block underneath it now yes, but it detects the air block under it, thus under the air block theres a floor.

PS: When those suggestions implemented, Ill go fork the plugin and changing the command to /wshop and translating into french. I already did that but atm I lost the source so I need to redo it

**Comment by tastybento** [comment]
Done with the latest version!

**Comment by TNTUP** [comment]
Another idea with this current release, like people wants to do the /wwarps <name> rather than /wshop (opens a gui), I know theres a setting for it but I want to keep that GUI and the classic way (like /wwarps list and /wwarps (Opens the GUI) then /wwarps <name>, that would be possible?
