### ISSUE TITLE
[ Request ] 1.14.x Support

### ISSUE THREAD

**Issue by AmazedMender16** [tastybento/welcomewarpsigns#3]
Hello,

Could we get an update to support 1.14.x or is it dead?

**Comment by krusic22** [comment]
Might want to check our my fork.
This version is dead in favor of the new version that only works as a BentoBox addon.

**Comment by Diclo** [comment]
but there would not be a version that would not take up bento, since that would only be for normal survival

**Comment by tastybento** [comment]
The latest release of Warps for BentoBox now supports operation in any world: https://github.com/BentoBoxWorld/Warps/releases/tag/1.8.1
As I'm only working on that version now, it'll be the way to go. You do not have to run any other addons if you don't wish, just BentoBox and then Warps.

**Comment by MrCetst** [comment]
Pls 1.16.5 update
